#include "fm_errors.h"


/*----------------------------------------------------------------------------*/
struct ERR_DESC
{
  fmerr_t err;
  char *msg;
};
/*----------------------------------------------------------------------------*/
static const struct ERR_DESC known_errors[] =
{
  {FM_OK  ,"No error"},
  {FME_HARDWARE, "Hardware error"},
  {FME_SOFTWARE, "Software error"},
  {FME_OS, "OS error"},
  {FME_INTERFACE, "Interface error"},

  {FME_RAM, "REM error"},
  {FME_NV_RAM, "NVRAM error"},
  {FME_FLASH, "FLASH error"},
  {FME_FISCAL, "Fiscal ROM error"},
  {FME_EJ, "Electronic journal error"},

  {FME_OVERFLOAT  ,"Numeric overfloat"},
  {FME_ZERODIVIDE ,"Divide by zero"},
  {FME_INVALIDPASS  ,"Invalid clerk password"},
  {FME_PERMDENIED   ,"Permission denied"},
  {FME_NOSUCHCLERK  ,"Clerk not programmed"},
  {FME_NOSUCHPLU  ,"PLU not programmed"},
  {FME_NOSUCHDEPT  ,"DEPT not programmed"},
  {FME_VALUEOUTOFRANGE  ,"Value out of range"},
  {FME_STRLENGTH ,"String length out of range"},
  {FME_NOSERIALNUM ,"No serial number in fiscal memory"},
  {FME_NOFISCALMODE ,"No fiscalisation data in fiscal memory"},
  {FME_NOSUCHSTORE ,"Store not found"},
  {FME_NOSUCHDISPENS ,"Dispenser not found"},
  {FME_NOSUCHNOZZLE ,"Nozzle not found"},
  {FME_NOTINIT ,"Data not initialized"},
  {FME_INVALIDPARAM  ,"Invalid parameter"},
  {FME_SETTINGS  ,"Invalid settings"},
  {FME_INPROGRESS, "Job in progress"},
  {FME_ABORTED, "Aborted job"},
  {FME_FUNCNOTFOUND, "Function not found"},
  {FME_NOSUCHGROUP,  "Product group not programmed"},
  {FME_PACKAGEREF,  "Invalid package reference"},
  {FME_REMAINLESS, "Amount greater then remain"},
  {FME_BASKETNOTFOUND, "Basket item not found"},
  {FME_BASKETCOUNT, "Basket item count out of range"},
  {FME_DISPENSEACTIVE, "Dispense active"},
  {FME_PAYMENTCOUNT, "Payment count out of range"},
  {FME_TRANSCOUNT  ,"Transaction count out of range"},
  {FME_DISCOUNT, "Discount error"},
  {FME_TAXNOTFOUND, "Tax group not found"},
  {FME_INVALIDPAYFORM, "Invalid payform"},
  {FME_INVALIDFORMATCPEC, "Invalid format specifier"},
  {FME_INVALIDOP, "Invalid operation"},
  {FME_INVALIDNUMBER, "Invalid number format"},
  {FME_CTRLERROR, "Controller error"},
  {FME_CTL_EMAXDRV, "CTRL: Driver count out of range"},
  {FME_CTL_EMAXPUMP, "CTRL: Dispenser count out of range"},
  {FME_CTL_ENODRV, "CTRL: Invalid driver index"},
  {FME_CTL_ENOPUMP, "CTRL: Invalid dispenser index"},
  {FME_CTL_ENODRVF, "CTRL: Driver not found"},
  {FME_CTL_ENOCOM, "CTRL: Error open COM"},
  {FME_CTL_EFAILED, "CTRL: Driver error"},
  {FME_CTL_ENOCMD, "CTRL: Invalid command"},
  {FME_CTL_ESYS, "CTRL: System error"},
  {FME_MULTIPAYMENT, "Multipayment error"},
  {FME_PUMPBUSY, "Pump is busy"},
  {FME_BASKETLOCKED, "Basket is locked"},
  {FME_INVALID_PAYDOUT, "Paydout greater then drawer sum"},
  {FME_NOSUCHEMITENT, "Emitent not programmed"},
  {FME_FMDATA, "Fiscal memory data corrupted"},
  {FME_NOBUSINESATTR, "Business attributes not programmed"},
  {FME_MAXCLEANCOUNT, "Maximum registers clean count reached"},
  {FME_INVALIDREGEXP, "Invalid regular expression"},
  {FME_INVALIDSTRING, "String not in trapharet"},
  {FME_INVALIDPAYRET, "Invalid pay return operation"},
  {FME_STRINGNOTFOUND, "String resource not found"},
  {FME_DATELESSFM, "Date less then last Fiscal record"},
  {FME_PLUATTRCHANGE, "Try to change PLU attributes"},
  {FME_SESSIONTIME, "Session time riched"},
  {FME_OPDISABLED, "Operation disabled before Z"},
  {FME_FMFULL, "Fiscal memory full"},
  {FME_EJFULL, "Electronic journal full"},
  {FME_PRN_POWER_OFF, "Printer power off"},
  {FME_PRN_SYSTEM, "Printer system error"},
  {FME_PRN_INIT, "Printer init error"},
  {FME_PRN_COVER, "Printer cover open"},
  {FME_PRN_OVERHEAT, "Overheat of printhead"},
  {FME_PUMP_IS_OFFLINE, "Pump is offline"},
  {FME_PLU_DELETE, "PLU delete error"},
  {FME_STORE_DELETE, "Store delete error"},
  {FME_CONTRACTNOTFOUD, "Contract not found"},
  {FME_CONTRACTBALANCE, "Contract limit reached"},
  {FME_CONTRACTPLU, "Contract product incompatibility"},
  {FME_INVALIDEXCISE, "Invalid excise operation"},

  {FME_PRNERR, "Printer error"},
  {FME_PRNPAPER, "Paper out"},
  {FME_PRNBUSY, "Printer busy"},
  {FME_POWER, "Power failure"},
  {FME_RTC, "Real time clock error"},
  {FME_CD, "Customer display error"},

  {FME_INVALIDHANDLE, "Invalid handle"},
  {FME_INVALIDANSWER, "Invalid answer"},
  {FME_BUFFERTOOSMALL, "Buffer too small"},
  {FME_STX_TIMEOUT, "STX timeout"},
  {FME_HEAD_TIMEOUT, "Packet head timeout"},
  {FME_DATA_TIMEOUT, "Packet data timeout"},
  {FME_CRC_TIMEOUT, "Packet CRC timeout"},
  {FME_CRC_ERROR, "Packet CRC error"},
  {FME_ETX_TIMEOUT, "Packet ETX timeout"},
  {FME_SIZE_ERROR, "Packet size error"},
  {FME_NAK_RECEIVED, "NAK received"},
  {FME_HEAD_ERROR, "Packet head error"},
  {FME_PACK_ID, "Invalid packet ID"},
  {FME_CONNECTION, "Connection to host error"},

  {FME_OPENDATA, "Error open file"},
  {FME_WRITEDATA, "Error write file"},
  {FME_READDATA, "Error read file"},
  {FME_OPENCOM, "Error open COM port"},
  {FME_MUTEX, "Error create mutex"},
  {FME_THREAD, "Error create thread"},
  {FME_MALLOC, "Memory allocate error"},

  {FME_MODEM, "Fiscal modem error"},
  {FME_MDM_NOT_READY, "Modem not ready"},
  {FME_MDM_NOT_PERSONALISED, "Modem not personalised"},
  {FME_MDM_INVALID_FORMAT, "Modem: invalid format"},
  {FME_MDM_UNCNOWN_DOC_TYPE, "Modem: invalid doc type"},
  {FME_MDM_UNRNOWN_REC_TYPE, "Modem: invalid record type"},
  {FME_MDM_INVALID_DATE, "Modem: invalid date or time"},
  {FME_MDM_INVALID_DOC_ID, "Modem: invalid doc id"},
  {FME_MDM_INVALID_REC_NUM, "Modem: Invalid record number"},
  {FME_MDM_LOST_RECORD, "Modem: lost record(s)"},
  {FME_MDM_RECNUM_RICHED, "Modem: record nom reached"},
  {FME_MDM_INVALID_COMMAND, "Modem: invalid command"},
  {FME_MDM_72H_ERROR, "Modem: doc transmit pause riched 72h"},
  {FME_MDM_COM_OPEN_ERROR, "Modem: Invalid handle"},
  {FME_MDM_INVALIDANSWER, "Modem: Invalid answer"},
  {FME_MDM_BUFFERTOOSMALL, "Modem: Buffer too small"},
  {FME_MDM_STX_TIMEOUT, "Modem: STX timeout"},
  {FME_MDM_HEAD_TIMEOUT, "Modem: Packet head timeout"},
  {FME_MDM_DATA_TIMEOUT, "Modem: Packet data timeout"},
  {FME_MDM_ACK_TIMEOUT, "Modem: ACK timeout"},
  {FME_MDM_CRC_ERROR, "Modem: Packet CRC error"},
  {FME_MDM_ETX_TIMEOUT, "Modem: Packet ETX timeout"},
  {FME_MDM_SIZE_ERROR, "Modem: Packet size error"},
  {FME_MDM_NAK_RECEIVED, "Modem: NAK received"},
  {FME_MDM_HEAD_ERROR, "Modem: Packet head error"},
  {FME_MDM_PACK_ID, "Modem: Invalid packet ID"},
  {FME_MDM_COM_WRITE, "Modem: Serial write error"},
  {FME_KSEF_XML_PARSE, "KSEF: XML parse error"},

  {FME_KSEF_NO_PERSON, "KSEF: Module not prsonalised"},
  {FME_KSEF_SAM_NO_PERSON, "KSEF: SAM-module not prsonalised"},
  {FME_KSEF_NT_SAM_LIMIT ,"KSEF: NT_SAM limit"},
  {FME_KSEF_SD_BAD_FORMAT ,"KSEF: SD card bad format"},
  {FME_KSEF_SD_ERROR ,"KSEF: SD error"},
  {FME_KSEF_SESSION_LIMIT ,"KSEF: Session limit"},
  {FME_KSEF_MEMORY_FAULT ,"KSEF: Memory limit"},
  {FME_KSEF_SAM_FAULT, "KSEF: SAM fault"},
  {FME_KSEF_RTC_FAULT, "KSEF: RTC fault"},
  {FME_KSEF_ETH_NO_CONNECT, "KSEF: ETH no connect"},
  {FME_KSEF_ETH_WRITE_FAULT, "KSEF: ETH write fault"},
  {FME_KSEF_ETH_READ_FAULT, "KSEF: ETH read fault"},
  {FME_KSEF_ETH_RSPNS_FAULT, "KSEF: Response fault"},
  {FME_KSEF_STR_DATE_FAULT, "KSEF: Invalid date"},
  {FME_KSEF_SRV_STR_DATE_FAULT, "KSEF: Server invalid date"},
  {FME_KSEF_XML_FAULT, "KSEF: XML error"},
  {FME_KSEF_SAM_NOT_RESPONSE, "KSEF: SAM not response"},
  {FME_KSEF_HASHHARD_FAULT, "KSEF: HASH hard fault"},
  {FME_KSEF_HASH_FAULT, "KSEF: HASH fault"},
  {FME_KSEF_PARAM_FAULT, "KSEF: invalid param"},
  {FME_KSEF_DPA_TLG_LENGTH, "KSEF: Telegramm length"},
  {FME_KSEF_DPA_TLG_SEQUENCE, "KSEF: Telegramm sequence"},
  {FME_KSEF_DPA_TLG_UNKNOWN, "KSEF: Telegramm number unknown"},
  {FME_KSEF_DPA_TLG_VERSION, "KSEF: Telegramm version"},
  {FME_KSEF_DPA_TLG_RRO_ID, "KSEF: Telegramm RRO ID"},
  {FME_KSEF_DPA_TLG_SAM_ID, "KSEF: Telegramm SAM ID"},
  {FME_KSEF_DPA_TLG_NT_SAM, "KSEF: Telegramm NT_SAM"},
  {FME_KSEF_DPA_TLG_MAC, "KSEF: Telegramm MAC"},
  {FME_KSEF_DPA_TLG_WTX, "KSEF: Telegramm WTX"},
  {FME_KSEF_DPA_TLG_BREAK, "KSEF: Telegramm break"},
  {FME_KSEF_DPA_FAULT, "KSEF: DPA fault"},
  {FME_KSEF_DPA_NEED_REPEAT_TELEGRAMM, "KSEF: Connecting session error"},
  {FME_KSEF_DOC_LIMIT, "KSEF: Disk limit reached"},
  {FME_KSEF_DPA_TLG_NEXT, "KSEF: EXC_NEXT server exception"},
  {FME_KSEF_IDDEV_ABSENT, "KSEF: ID_DEV absent on KSEF SD"},
  {FME_KSEF_IDSAM_ABSENT, "KSEF: SAM not initialised"},
  {FME_KSEF_NOT_EQUAL_IDSAM_IDDEV, "KSEF: ID_DEV not equal ID_SAM"},
  {FME_KSEF_SAM_INIT_FAULT, "KSEF: SAM init fault"},
  {FME_KSEF_SAM_BUSY, "KSEF: Busy of DPA server communication"},


  {FME_KSEF_DI_ERROR, "KSEF: Document ID sequency error"},

  {FME_KSEF_XML_PARSE, "KSEF: XML parse error"},
  {FME_KSEF_ERROR, "KSEF: KSEF error"},


  {FME_SAM_NO_REGISTRATION, "KSEF: SAM ANSWER no registration"},
  {FME_SAM_NT_SAM_LIMIT, "KSEF: SAM ANSWER NT limit"},
  {FME_SAM_KEY_NOT_SUPPORT, "KSEF: SAM ANSWER key not supported"},
  {FME_SAM_SYS_KEY_NOT_SUPPORT, "KSEF: SAM ANSWER sys key not supported"},
  {FME_SAM_MAC_ERROR, "KSEF: SAM ANSWER MAC error"},
  {FME_SAM_ID_TERM_NOT_VALID, "KSEF: SAM ANSWER ID term not valid"},
  {FME_SAM_FILE_END, "KSEF: SAM ANSWER file end"},
  {FME_SAM_OK_REPEAT, "KSEF: SAM ANSWER OK repeat"},
  {FME_SAM_BAD_AUTH, "KSEF: SAM ANSWER bad auth"},
  {FME_SAM_BAD_CRC, "KSEF: SAM ANSWER bad CRC"},
  {FME_SAM_BAD_LENGTH, "KSEF: SAM ANSWER bad length"},
  {FME_SAM_COMMAND_NOT_ALLOWED, "KSEF: SAM ANSWER command not allowed"},
  {FME_SAM_COMMAND_NOT_SUPPORT, "KSEF: SAM ANSWER command not support"},
  {FME_SAM_ACCESS_DENIED, "KSEF: SAM ANSWER access denied"},
  {FME_SAM_BLOCK_AUTH_METHOD, "KSEF: SAM ANSWER auth metod blocked"},
  {FME_SAM_BLOCK_FILE, "KSEF: SAM ANSWER file blocked"},
  {FME_SAM_POOR_CONDITIONS, "KSEF: SAM ANSWER poor conditions"},
  {FME_SAM_NOT_SECURE_MESSAGING, "KSEF: SAM ANSWER not ecure messaging"},
  {FME_SAM_BAD_SECURE_MESSAGING, "KSEF: SAM ANSWER bad secure messaging"},
  {FME_SAM_BAD_PARAMS, "KSEF: SAM ANSWER bad params"},
  {FME_SAM_FUNC_NOT_SUPPORT, "KSEF: SAM ANSWER function not supported"},
  {FME_SAM_FILE_NOT_FOUND, "KSEF: SAM ANSWER file not found"},
  {FME_SAM_REC_NOT_FOUND, "KSEF: SAM ANSWER record not found"},
  {FME_SAM_BAD_FILE_SIZE, "KSEF: SAM ANSWER bad file size"},
  {FME_SAM_BAD_P1_P2, "KSEF: SAM ANSWER bad P! P2"},
  {FME_SAM_DATA_NOT_FOUND, "KSEF: SAM ANSWER data not found"},
  {FME_SAM_NOT_SUPPORT_P1_P2, "KSEF: SAM ANSWER not support P1 P2"},
  {FME_SAM_INS_NOT_SUPPORT, "KSEF: SAM ANSWER INS not support"},
  {FME_SAM_CLA_NOT_SUPPORT, "KSEF: SAM ANSWER CLA not support"},
  {FME_SAM_INCORRECT_COMMAND, "KSEF: SAM ANSWER incorrect command"},

  {FME_CARD_ERROR, "Card error"}


};
/*----------------------------------------------------------------------------*/
static const struct ERR_DESC known_wheres[] =
{
  {FMW_BASKET, "Basket"},
  {FMW_BILL, "Bill"},
  {FMW_CD, "Customer display"},
  {FMW_CLERK, "Clerk"},
  {FMW_DISPENSER, "Dispenser"},
  {FMW_EJ, "Electronic journal"},
  {FMW_EMITENT, "Emitent"},
  {FMW_FINDATA, "Fin data"},
  {FMW_FISCAL, "Fiscal"},
  {FMW_GOODS, "Goods"},
  {FMW_INIT, "Init"},
  {FMW_PAYFORM, "Pay form"},
  {FMW_PROFILE, "Profile"},
  {FMW_REPORT, "Report"},
  {FMW_STORE, "Store"},
  {FMW_TAX, "Tax"},
  {FMW_TIME, "Time"},
  {FMW_VARS, "Vars"},
  {FMW_DISCOUNT, "Discount"},
  {FMW_DOC, "Doc"},
  {FMW_PAYMENT, "Payment"},
  {FMW_PRINT, "Print"},
  {FMW_API, "API"},
  {FMW_CLIENT, "Client"},
  {FMW_SERVER, "Server"},
  {FMW_PSF, "PSF"},
  {FMW_MODEM, "Modem"},
  {FMW_KSEF, "KSEF"},
  {FMW_KSEF_XML, "KSEF_XML"},
  {FMW_KSEF_API, "KSEF_API"},
  {FMW_NET, "NET"},
  {FMW_VERIFONE, "VERIFONE"},
  {FMW_BARCODE, "BARCODE"}

};
/*----------------------------------------------------------------------------*/
/* Return standard error description.*/
char *fm_str_error(fmret_t err)
{
  int i;
  err = FME_WHAT(err);
  for(i = 0; i < sizeof(known_errors)/sizeof(struct ERR_DESC); i++)
    if(err == known_errors[i].err)
      return known_errors[i].msg;
  return "Unknown error";
}
/*----------------------------------------------------------------------------*/
char *fm_str_where(fmret_t err)
{
  int i;
  err = FME_WHERE(err);
  for(i = 0; i < sizeof(known_wheres)/sizeof(struct ERR_DESC); i++)
    if(err == known_wheres[i].err)
      return known_wheres[i].msg;
  return "";
}
/*----------------------------------------------------------------------------*/

